### ISSUE TITLE
Reproducibility of designs with parallel computing?

### ISSUE THREAD

**Issue by ugroempi** [tylermorganwall/skpr#33]
Hi Tyler,

I find that `gen_design` produces different designs based on the same random seed, if I use parallel computing (just run the optimization code below twice, the same designs should give the same printed output). With `parallel=FALSE`, the designs are the same. Is the lack of reproducibility for parallel computing unavoidable?

`## the code`
`## candidate points, these are factors named A to E`
`cand <- DoE.base::fac.design(nlevels=c(2,2,4,4,4), randomize=FALSE)`
`## optimization`
`set.seed(2479)`
`system.time(skpr128D <- gen_design(cand, ~(A+B+C+D+E)^2, 128, repeats=10, parallel=TRUE))`
`## design properties`
`DoE.base::GWLP(skpr128D)`
`DoE.base::SCFTs(skpr128D)`

Best, Ulrike

P.S.: And, by the way, on the problem above, function `optFederov` from package AlgDesign appears to be much faster (I used 100 repeats in both cases, which gave me 7s in AlgDesign (using a single core) and 44s in skpr (using all four cores of my machine).

**Comment by tylermorganwall** [comment]
Hi Ulrike,

I pushed a fix which should take care of the parallel reproducibility issue. It should now return the same design for the same seed when `parallel=TRUE`. 

As for speed, I profiled the C code and the issue lies in slow matrix multiplication routines in the underlying BLAS libraries. I tried this with both the base R BLAS as well as the Intel MKL libraries, and I'm getting about the same results as you did with the base R libraries (and about 2x faster results with the MKL libraries: 44 seconds on two logical cores). Bob Wheeler hand coded AlgDesign's underlying linear algebra routines, and they thus are very well optimized for the task at hand, at the significant expense of readability--the complexity of AlgDesign's code base was one of the inspirations for building this package. 

Nevertheless, I will look at his code and see if there are any optimizations that would be possible to port over for the D-optimal case.

**Comment by tylermorganwall** [comment]
George and I took an initial look at the issue today and we figured out some bookkeeping  improvements in the algorithm for D-optimal designs that should decrease the run-time by more than 50%. 

On my four-core machine (macOS, default BLAS), the run-time for the 100 repeat design went as follows:

With `parallel=TRUE`:
38s -> 16s

With `parallel=FALSE`:
155s -> 61s

**Comment by ugroempi** [comment]
Thanks for fixing the reproducibility!

Time is also much faster on my Windows 7 machine, but still way to go for competing with AlgDesign: 
skpr, `parallel=TRUE` with four cores: 20.22s
skpr, `parallel=FALSE`: 66.81s
AlgDesign (no parallel computing): 7.23s

I haven't done a systematic study on design quality, but it seemed also easier for me to obtain a design with 100% D-efficiency with AlgDesign (the proportion of designs (100 repeats) that were exactly resolution V when running without a seed seemed higher for AlgDesign than for skpr). I always called `optFederov` through DoE.wrapper (`system.time(ausd <- DoE.wrapper::Dopt.design(128, formula=~.^2, nlevels=c(2,2,4,4,4), qual=TRUE, nRepeats=100))`), but that shouldn't make a difference.

Best, Ulrike
