### ISSUE TITLE
aliaspower now relevant for D-optimality?

### ISSUE THREAD

**Issue by ugroempi** [tylermorganwall/skpr#36]
Hi Tyler,

I read in your NEWS file: "Changed optimal search algorithm to return design with best aliasing structure (as determined by the alias matrix) when there is a tie between optimal designs. Increases likelyhood of producing an orthogonal design."

Does this mean that the aliaspower is now relevant for optimality criteria other than Alias?

Best, Ulrike

**Comment by tylermorganwall** [comment]
Hi Ulrike,

Right now, it doesn't use the value of aliaspower when computing the alias matrix for the tie breaker (it uses the default value of 2). I believe using higher-order alias matrices would only be useful two designs had the same lower-order aliasing structures and were differentiated entirely by their higher-order terms. I haven't done any studies to see how often that case occurs, but I imagine it's not too often. If you think it might be useful, however, it would be a simple change to implement.

The main goal of the algorithm change was to help pick out the classically orthogonal design if one exists and was found (since they usually have a better screening structure than a non-classical algorithmically-produced optimal design).

**Comment by ugroempi** [comment]
Hi Tyler, 
I quite like your tie breaker, and I think that aliaspower 2 certainly covers the most important cases. I agree with you that optimizing higher order terms would not be of interest, as long as lower order ones can still be improved. 
If one can afford a large design for which e.g. resolution V would be possible, and one requests a full quadratic model, perhaps a higher order tie breaker could be used to find a resolution V design faster?
Best, Ulrike

**Comment by tylermorganwall** [comment]
With the next version's addition of an advanced interface including user-defined tolerances (from [the other issue](https://github.com/tylermorganwall/skpr/issues/36)) I will also include an option to change the tie-breaker aliaspower. The tie-resolution code currently doesn't offer any speed-up (as the equality check only comes after all the design search has been done), but specifying the tolerance/max iterations might provide what you're looking for.

**Comment by tylermorganwall** [comment]
Hi Ulrike,

The latest version 0.46.0 now has an interface to specify the alias power use in tie breaking. You can change it by passing in a named list into gen_design specifying "alias_tie_power".

e.g.
`gen_design(..., advancedoptions = list("alias_tie_power" = 3))`

**Comment by ugroempi** [comment]
Hi Tyler,
thanks, I'll be curious to see it at work!
Best, Ulrike
