### ISSUE TITLE
Control of tolerances (and number of iterations)

### ISSUE THREAD

**Issue by ugroempi** [tylermorganwall/skpr#37]
Hi Tyler,

I have been playing with skpr's new alias-based tie resolution, and find that it does lead to improved number of length 3 words (A_3) for increased `repeats`. However, there are occasional dips, where A_3 after more repeats (e.g. 2000) is worse than that after fewer repeats (e.g. 1000), even though the design was already orthogonal (except for small numeric inaccuracies); presumably, this happens because irrelevant and numerically small differences prevent the designs to be considered as tied?

I was wondering why gen_design does not accept any user inputs on tolerance (and also on maximum number of iterations within a repeat, like `maxIterations` for `optFederov` from AlgDesign). 

Best, Ulrike

**Comment by tylermorganwall** [comment]
Hi Ulrike,

Can you post example code? If the optimality criteria between the two designs are exactly the same, the tie-resolution code should pick the design with the better aliasing structure. If it doesn't, it might be a bug. Another alternative is that the new (worse with regards to A_3) design has a very marginally improved optimality criterion than the design with the previous design. In that case, the tie-resolution code will never be called and it will pick the more optimal (but worse with regards to A_3) design.

As for tolerance and maxiterations, I didn't make it available as an argument as most practitioners only need it to be good enough, and I did not know how much interest there was in being able to adjust it. Since you've expressed interest, I will include an interface that will allow access to those options in the next version.

**Comment by ugroempi** [comment]
Hi Tyler,

I'm quite sure it's not a bug but a small difference in the criterion; this is what set me off thinking about tolerances, because I thought that such a small difference is likely numeric noise and should be treated as zero.
I used this code with two cores:
`set.seed(2137)`
`system.time(ausskprD24 <- gen_design(cand24, ~A+B+C+D+E+F, 24, optimality="D", `
`     repeats=200, parallel=TRUE))`
A_3 with 2000 repeats was worse than with 1000, before getting better again.

And the other reason for thinking about tolerances / iteration numbers was that it might be useful to make rules for convergence less strict in order to allow more repeats in the same run time. 

Best, Ulrike

**Comment by tylermorganwall** [comment]
Hi Ulrike,

The latest version 0.46.0 now has an interface to specify the tolerance used in the design search, as well as the tolerance when determining whether two designs are tied. These are specified within the list passed to advancedoptions as "design_search_tolerance" and "alias_tie_tolerance", respectively. 

e.g.
`gen_design(..., advancedoptions = list("design_search_tolerance" = 10e-6))` would stop the design search when the fractional increase is below `10e-6`.

"alias_tie_tolerance" is specified as a percentage for D-optimal designs, and is the raw criteria value for all other criteria. So to consider designs within 5% D-optimal a tie, you would pass in `advancedoptions = list("alias_tie_tolerance" = 0.05)`

**Comment by ugroempi** [comment]
Hi Tyler,
`alias_tie_tolerance=0.1`  improves the behavior of D-optimal designs for the above 24 run example, A3 is continually driven down with increasing run size (though the alias optimal design is much more successful). I would have expected smaller tolerances (e.g. 0.01) to also do the job, but they don't.
Best, Ulrike

**Comment by tylermorganwall** [comment]
Good to know! The large number required to make a difference in A3 is consistent with what I found with alias optimal designs, where minDopt originally defaulted at 0.95 but didn't work very well. It did a much more consistent job finding good screening designs when I lowered it to 0.80. Maximizing alias-optimality directly should of course do a better job finding screening designs, but it's interesting the D-optimal search is in fact ending up in local minima with better aliasing properties.

**Comment by ugroempi** [comment]
I have now also played a little with `design_search_tolerance`. For a difficult  (in terms of finding an orthogonal design) example with 96 runs, four 2-level, one 3-level and two 4-level factors, I found that a really large tolerance of 0.5 with 1000 repeats (1250s) takes about as long as no specification of `design_search_tolerance` with 500 repeats (1350s) and produces a slightly better result: 500 repeats give (A_2,A_3,A_4)=(0.00608, 0.1675, 1.4670), while 1000 repeats with the high tolerance give (A_2,A_3,A_4)=(0.0000,  0.1354, 1.5556). In both cases, I had specified `alias_tie_power=2` and `alias_tie_tolerance=0.2`. I know that A_3=0 is possible, I don't know about the best possible A_4 (`alias_tie_power=3` did not change anything; `design_search_tolerance=0.2` did not sufficiently reduce run time).

I'm quite surprised that such a large `design_search_tolerance` is needed for achieving a substantial reduction in run time, given that run times per repeat are much shorter in AlgDesign (about 500s for 1000 repeats with a single core, compared to about 2700s with two cores for skpr with default `design_search_tolerance` settings). 

Best, Ulrike

**Comment by tylermorganwall** [comment]
It doesn't surprise me that the tolerance argument doesn't decrease the runtime for smaller values. In my trials, modified Fedorov's algorithm tends to converge fairly quickly to a minimum/maximum (whether it be local or global). Comparing the change to the tolerance is only done once every **n**\***N** runs, where **n** is the number of runs and **N** is the number of points in the candidate set. Thus, you only gain a significant speed-up if the you manage to skip a full iteration of modified Fedorov's, which won't be the case if the criterion is increasing quickly.

On the topic of speed compared to AlgDesign
-------------------------------------------

AlgDesign is faster than skpr, but that speed comes at a price--mainly, much **much** worse designs if the candidate set is not specified exactly right. In addition, AlgDesign-produced I-optimal designs are almost always inferior due to the algorithm used, regardless of how you try to work around its limitations. Basically, AlgDesign designs are only truly optimal for a few cases: D-optimal designs much smaller than the candidate set, where you built the candidate set without including design points that won't be in the final design.

AlgDesign samples from the candidate set without replacement, which is one reason it can produce designs with smaller candidate sets so quickly; the closer a design is in size to the candidate set, the quicker the search will execute. This is because every run you add to the design effectly removes an entry from the candidate set, since once it is set it will not be looked at in future iterations. This means, however, two things: firstly, you can't produce an optimal design larger than the candidate set without rbind-ing multiple versions of the candidate set together (which scales poorly, and was one of the reasons I decided to develop skpr). Secondly, unless one intimately knows what points will be included in the final design--which means they probably don't need an algorithmically-produced design--AlgDesign can produce some **very** poor designs.

skpr, on the other hand, just performs a modified Fedorov's search \[Cook, R. D. and Nachtsheim, C. J. (1980), “A Comparison of Algorithms for Constructing Exact D-Optimal Designs,” Technometrics, 22, 315–324.\] following the cited algorithm.

Here is an example. I first will generate a small design with which AlgDesign and skpr perform equally well. In cases like this (small design, larger candidate set, D-optimal), AlgDesign will indeed be faster and produce the same design as skpr.

``` r
library(skpr)
library(AlgDesign)
library(magrittr)
library(knitr)

set.seed(1)
#Create a small candidate set of only points on the extrema 
candset = expand.grid(X1=c(1,-1),X2=c(1,-1),X3=c(1,-1))
alg_design = optFederov(frml=~X1+X2+X3, data=candset, nTrials = 6, nRepeats=20, criterion = "D")$design
skpr_design = gen_design(candset, ~X1+X2+X3, 6, repeats = 20, optimality = "D")

#Calculate D-optimality for each design
eval_design(alg_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 94.2809

``` r
eval_design(skpr_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 94.2809

Now, let's say the user overspecifies their candidate set by adding a center point to each factor, and also increases the number of runs. AlgDesign, by default, will not return the D-optimal design, which consists only of extreme points. I chose the most extreme example here of 27 runs (equaling the number of entries in the candidate set) to illustrate the point:

``` r
set.seed(1)
candset = expand.grid(X1=c(1,0,-1),X2=c(1,0,-1),X3=c(1,0,-1))
alg_design = optFederov(frml=~X1+X2+X3, data=candset, nTrials = 27, nRepeats=20, criterion = "D")$design
skpr_design = gen_design(candset, ~X1+X2+X3, 27, repeats = 27, optimality = "D")

eval_design(alg_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 73.77879

``` r
eval_design(skpr_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 99.78323

Comparing the two designs, we see the AlgDesign indeed just extracted all entries from the candidate set. This is due to sampling the candidate set without replacement, and is not the optimal design given the inputs. AlgDesign will produce the optimal design for everything 8 runs and below, and a non-optimal design for everything greater than 8 runs. Here are the designs:

``` r
colnames(alg_design) = paste0("Alg_",colnames(alg_design))
colnames(skpr_design) = paste0("skpr_",colnames(skpr_design))
knitr::kable(cbind("run"=1:27,alg_design,skpr_design))
```

|  run|  Alg\_X1|  Alg\_X2|  Alg\_X3|  skpr\_X1|  skpr\_X2|  skpr\_X3|
|----:|--------:|--------:|--------:|---------:|---------:|---------:|
|    1|        1|        1|        1|         1|        -1|        -1|
|    2|        0|        1|        1|         1|        -1|        -1|
|    3|       -1|        1|        1|         1|         1|        -1|
|    4|        1|        0|        1|         1|         1|         1|
|    5|        0|        0|        1|        -1|         1|        -1|
|    6|       -1|        0|        1|        -1|        -1|        -1|
|    7|        1|       -1|        1|         1|        -1|         1|
|    8|        0|       -1|        1|        -1|        -1|         1|
|    9|       -1|       -1|        1|         1|         1|        -1|
|   10|        1|        1|        0|        -1|         1|         1|
|   11|        0|        1|        0|        -1|        -1|         1|
|   12|       -1|        1|        0|        -1|         1|        -1|
|   13|        1|        0|        0|        -1|         1|         1|
|   14|        0|        0|        0|         1|        -1|         1|
|   15|       -1|        0|        0|        -1|        -1|         1|
|   16|        1|       -1|        0|        -1|        -1|        -1|
|   17|        0|       -1|        0|        -1|         1|         1|
|   18|       -1|       -1|        0|        -1|        -1|        -1|
|   19|        1|        1|       -1|         1|        -1|         1|
|   20|        0|        1|       -1|         1|         1|        -1|
|   21|       -1|        1|       -1|         1|         1|         1|
|   22|        1|        0|       -1|        -1|         1|        -1|
|   23|        0|        0|       -1|         1|         1|         1|
|   24|       -1|        0|       -1|         1|        -1|        -1|
|   25|        1|       -1|       -1|        -1|         1|        -1|
|   26|        0|       -1|       -1|         1|        -1|        -1|
|   27|       -1|       -1|       -1|         1|         1|         1|

We can work around this in AlgDesign by replicating the candidate set--but this will scale poorly for larger candidate sets. Here, you need four replicates to match skpr's output. The user would have to know to do this iteratively until no improvement was seen.

``` r
set.seed(1)
candset = expand.grid(X1=c(1,0,-1),X2=c(1,0,-1),X3=c(1,0,-1))
alg_design = optFederov(frml=~X1+X2+X3, data=rbind(candset,candset,candset,candset), nTrials = 27, nRepeats=20, criterion = "D")$design
skpr_design = gen_design(candset, ~X1+X2+X3, 27, repeats = 20, optimality = "D")

eval_design(alg_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 99.78323

``` r
eval_design(skpr_design,~X1+X2+X3,0.2) %>% attr("D")
```

    ## [1] 99.78323

That's the first major limitation of AlgDesign.

AlgDesign's algorithm also leads to issues with I-optimal designs, which tend to have repeated center points. Here, we generate a response surface design with only 8 runs, and input a well-reasoned candidate set for the model consisting of center points and extrema:

``` r
set.seed(1)
candset = expand.grid(X1=c(1,0,-1),X2=c(1,0,-1))
alg_design = optFederov(frml=~X1+X2+I(X1^2)+I(X2^2), data=candset, nTrials = 8, nRepeats=20, criterion = "I")$design
skpr_design = gen_design(candset, ~X1+X2+I(X1^2)+I(X2^2), trials = 8 , repeats = 20, optimality = "I")

eval_design(alg_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.5333333

``` r
eval_design(skpr_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.4638889

``` r
colnames(alg_design) = paste0("Alg_",colnames(alg_design))
colnames(skpr_design) = paste0("skpr_",colnames(skpr_design))
knitr::kable(cbind(alg_design,skpr_design))
```

|     |  Alg\_X1|  Alg\_X2|  skpr\_X1|  skpr\_X2|
|-----|--------:|--------:|---------:|---------:|
| 1   |        1|        1|         0|         0|
| 2   |        0|        1|         0|        -1|
| 3   |       -1|        1|         1|         0|
| 4   |        1|        0|         0|         0|
| 5   |        0|        0|        -1|         0|
| 7   |        1|       -1|         0|         1|
| 8   |        0|       -1|         1|         1|
| 9   |       -1|       -1|        -1|        -1|

AlgDesign here performs significantly worse than skpr, even when the number of runs is fewer than the number of entries in the candidate set. One might think that replicating the candidate set could fix this issue--but it doesn't. Here, I replicate the candidate set once (which should be enough to match skpr's performance given the difference is a single run) and perform the search again:

``` r
set.seed(1)
candset = expand.grid(X1=c(1,0,-1),X2=c(1,0,-1))
alg_design = optFederov(frml=~X1+X2+I(X1^2)+I(X2^2), data=rbind(candset,candset), nTrials = 8, nRepeats=20, criterion = "I")$design
skpr_design = gen_design(candset, ~X1+X2+I(X1^2)+I(X2^2), trials = 8 , repeats = 20, optimality = "I")

eval_design(alg_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.7166667

``` r
eval_design(skpr_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.4638889

``` r
colnames(alg_design) = paste0("Alg_",colnames(alg_design))
colnames(skpr_design) = paste0("skpr_",colnames(skpr_design))
knitr::kable(cbind(alg_design,skpr_design))
```

|     |  Alg\_X1|  Alg\_X2|  skpr\_X1|  skpr\_X2|
|-----|--------:|--------:|---------:|---------:|
| 1   |        1|        1|        -1|         0|
| 3   |       -1|        1|         0|         0|
| 7   |        1|       -1|         1|         0|
| 8   |        0|       -1|        -1|         1|
| 9   |       -1|       -1|         1|        -1|
| 11  |        0|        1|         0|        -1|
| 13  |        1|        0|         0|         0|
| 15  |       -1|        0|         0|         1|

No such luck. We can replicate the candidate set as many times as we want and increase nRepeats to a large number, but AlgDesign will not add the extra centerpoint needed to find the best I-optimal design.

``` r
set.seed(1)
candset = expand.grid(X1=c(1,0,-1),X2=c(1,0,-1))
alg_design = optFederov(frml=~X1+X2+I(X1^2)+I(X2^2), data=rbind(candset,candset,candset,candset,candset,candset), nTrials = 8, nRepeats=10000, criterion = "I")$design
skpr_design = gen_design(candset, ~X1+X2+I(X1^2)+I(X2^2), trials = 8 , repeats = 20, optimality = "I")

eval_design(alg_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.7166667

``` r
eval_design(skpr_design,~X1+X2+I(X1^2)+I(X2^2),0.2) %>% attr("I")
```

    ## [1] 0.4638889

I haven't looked closely at the AlgDesign code to figure out where the algorithm differs, but it is not returning the optimal design given the inputs.

I hope this answers your question on why skpr is slower than AlgDesign--skpr sacrifices speed to produce better designs for a much wider range of inputs, without requiring the end user to have enough expertise in constructing experimental designs that they know how to construct the candidate set given the model.

**Comment by ugroempi** [comment]
Thanks for the detailed considerations! I now understand about the search tolerances.

Actually, I am not much of an optimal design person, I only ever used D-optimal designs, and never for situations where the candidate set might be less than twice the size of the experiment (it is often much bigger than that). For "my" situations, you normally benefit from all runs being distinct, so that AlgDesigns sampling without replacement behavior is what I am looking for. For relatively complicated situations, however, I end up getting non-orthogonal designs, and I very much like skpr's ability to resolve ties by the alias behavior, and to produce Alias optimal designs.

I guess the conclusion from your explanations could be to use the design produced by AlgDesign (with large nRepeats), if it is satisfactory and to resort to skpr otherwise (and probably to not use AlgDesign for I-optimal designs). Once skpr has stabilized, I might include it into DoE.wrapper ...

**Comment by tylermorganwall** [comment]
That would be a good takeaway! AlgDesign is a fast and powerful tool for users who:

1) Only want D-optimal designs.
2) Are producing designs much smaller than the candidate set with no chance of repeating points.
3) Already developed a strong intuition and understanding of DoE, and thus can specify an appropriate candidate set for their model and can recognize when a design is likely not optimal. 

The goal in developing skpr is to provide a tool flexible and powerful enough for skilled users and researchers, while also providing basic utility and ease of use for practitioners who currently use programs like Design Expert or JMP to generate and evaluate optimal designs.

**Comment by ugroempi** [comment]
Hi Tyler, 
sounds great, I'll certainly try it out!
Best, Ulrike

**Comment by ugroempi** [comment]
Just tried a few examples. I see about factor 3-4 all right, but unfortunately I got (much) worse designs than before in all cases I tried, where I measure quality in terms of GWLP. None of the designs that were orthogonal before are orthogonal now ... This had (A3,A4,A5)=(20/9,32/9,11/9) before.

` require(DoE.base)`
`cand24 <- fac.design(c(2,2,2,2,3,4), randomize = FALSE)`
`set.seed(2137)`
` system.time(ausskprD24 <- gen_design(cand24, ~A+B+C+D+E+F, 24, optimality="D", repeats=2000,` `parallel=TRUE, advancedoptions = list(alias_tie_tolerance=0.1)))`
`GWLP(ausskprD24)`

**Comment by tylermorganwall** [comment]
You're right! A minus sign got flipped. It should be fixed in the latest version.

**Comment by ugroempi** [comment]
Great, back to good, and faster!

**Comment by ugroempi** [comment]
Would be good to document for which settings results for the same seed change versus earlier versions (it seems that they do when using same advanced options for D-optimal designs (?) and also for alias optimal designs (?)).

**Comment by tylermorganwall** [comment]
Could you post the Alias-optimal example that changed? I only changed one function that touched that search algorithm and I did not see any changes.

This latest update did in fact change the behavior with respect to the advanced options, but that's because the earlier method of comparing ties was flawed. There were a few bugs in total that all contributed to an incorrect calculation of the D-Efficiency, which then made the comparison to the alias_tie_tolerance incorrect. Those are now corrected and thus the output will definitely be different, but it's now displaying the correct behavior.

I will however write a few tests to generate designs with set seeds and will mark future updates if they alter the output for a set seed.

**Comment by ugroempi** [comment]
I can't post an example, because I am far away from my machine. But I didn't find any alias example with unchanged GWLP; maybe they all had aliaspoer 3.

**Comment by tylermorganwall** [comment]
You can install the older version (0.47.2) with the devtools call:

``` r
devtools::install_github("tylermorganwall/skpr", ref="9943a517b6d0e9f305433a62b229c9d55eac8cec")
```

I ran a few tests and did not see any differences (other than the alias_tie_tolerance examples, which will definitely be different). If you do find a difference, please tell me so I can try and figure out what's causing it :)

Old version (0.47.2):

``` r
devtools::install_github("tylermorganwall/skpr", ref="9943a517b6d0e9f305433a62b229c9d55eac8cec")
```

``` r
cand <- DoE.base::fac.design(nlevels=c(2,2,4,4,4), randomize=FALSE)
```

    ## creating full factorial with 256 runs ...

``` r
set.seed(2479)
skpr128D <- skpr::gen_design(cand, ~(A+B+C+D+E)^2, 128, repeats=10)
DoE.base::GWLP(skpr128D)
```

    ##        0        1        2        3        4        5 
    ## 1.000000 0.000000 0.000000 0.015625 0.062500 0.921875

``` r
set.seed(2479)
skpr128Alias <- skpr::gen_design(cand, ~(A+B+C+D+E), 36, repeats=10, optimality = "Alias")
DoE.base::GWLP(skpr128Alias)
```

    ##         0         1         2         3         4         5 
    ## 1.0000000 0.0308642 0.1419753 1.2654321 4.3641975 0.3086420

``` r
set.seed(2479)
skpr128Alias_3 <- skpr::gen_design(cand, ~(A+B+C)^2, 36, repeats=10, optimality = "Alias", aliaspower = 3,timer=TRUE)
DoE.base::GWLP(skpr128Alias_3)
```

    ##          0          1          2          3 
    ## 1.00000000 0.03703704 0.00000000 0.00000000

New version:

``` r
devtools::install_github("tylermorganwall/skpr")
```

``` r
cand <- DoE.base::fac.design(nlevels=c(2,2,4,4,4), randomize=FALSE)
```

    ## creating full factorial with 256 runs ...

``` r
set.seed(2479)
skpr128D <- skpr::gen_design(cand, ~(A+B+C+D+E)^2, 128, repeats=10)
DoE.base::GWLP(skpr128D)
```

    ##        0        1        2        3        4        5 
    ## 1.000000 0.000000 0.000000 0.015625 0.062500 0.921875

``` r
set.seed(2479)
skpr128Alias <- skpr::gen_design(cand, ~(A+B+C+D+E), 36, repeats=10, optimality = "Alias")
DoE.base::GWLP(skpr128Alias)
```

    ##         0         1         2         3         4         5 
    ## 1.0000000 0.0308642 0.1419753 1.2654321 4.3641975 0.3086420

``` r
set.seed(2479)
skpr128Alias_3 <- skpr::gen_design(cand, ~(A+B+C)^2, 36, repeats=10, optimality = "Alias", aliaspower = 3)
DoE.base::GWLP(skpr128Alias_3)
```

    ##          0          1          2          3 
    ## 1.00000000 0.03703704 0.00000000 0.00000000

**Comment by ugroempi** [comment]
I'll check it out, once I'm back. Maybe I messed something up, I did it in a hurry, because I wanted to finish it before going away.

**Comment by ugroempi** [comment]
Hi Tyler, I checked several instances and found that results for Alias optimality were unchanged. Sorry for the false alarm. Best, Ulrike

**Comment by tylermorganwall** [comment]
Good to know. Thanks for checking!

**Comment by tylermorganwall** [comment]
Hi Ulrike,
You might be interested to know that we made some major changes to the underlying linear algebra libraries in gen_design, and skpr should now be just about as fast as AlgDesign with a single core (and significantly faster with multiple cores).
Tyler

**Comment by ugroempi** [comment]
Hi Tyler, thanks for letting me know! Best, Ulrike 


Sent from my smartphone

-------- Ursprüngliche Nachricht --------
Von: tylermorganwall <notifications@github.com> 
Datum: 03.05.2018  23:34  (GMT+01:00) 
An: tylermorganwall/skpr <skpr@noreply.github.com> 
Cc: ugroempi <groemping@beuth-hochschule.de>, Author <author@noreply.github.com> 
Betreff: Re: [tylermorganwall/skpr] Control of tolerances (and number of
  iterations) (#37) 

Hi Ulrike,

You might be interested to know that we made some major changes to the underlying linear algebra libraries in gen_design, and skpr should now be just about as fast as AlgDesign with a single core (and significantly faster with multiple cores).

Tyler

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tylermorganwall/skpr","title":"tylermorganwall/skpr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tylermorganwall/skpr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tylermorganwall in #37: Hi Ulrike,\r\nYou might be interested to know that we made some major changes to the underlying linear algebra libraries in gen_design, and skpr should now be just about as fast as AlgDesign with a single core (and significantly faster with multiple cores).\r\nTyler"}],"action":{"name":"View Issue","url":"https://github.com/tylermorganwall/skpr/issues/37#issuecomment-386444247"}}}
