### ISSUE TITLE
Evaulating Power Design for Balanced Factors

### ISSUE THREAD

**Issue by Rookie323** [tylermorganwall/skpr#39]
First I want to say thank you for creating this package.  It was well needed.  

If you look at factor "y", I need to change the anticoef for conservative power.  Merely adding conservative = TRUE is not sufficient.  

I have only seen this issue when factors are balanced and parameter power are equal.  

Example: 
library(AlgDesign)
library(DoE.wrapper)
library(skpr)
library(mefa) # for the rep.data.frame function that replicates a data frame
library(lme4)
library(car)
library(tidyverse)

#Creating Design
cand.list <- expand.grid(x=c(1,2,3),y=c("Yes","No"),z= rep(c("A","B","C"),each=2))
rand.cand.list <- cand.list[sample(1:nrow(cand.list)),]
doe2 <- optFederov(~.^2 + I(x^2), data=rand.cand.list, nTrials=30, nRepeats = 1000)

#Attempting to calculate conservative power
doe.eval2 <- eval_design(doe2$design,
                        model=~ (x+y+z)^2 + I(x^2),
                        alpha=.2, effectsize = 1.5,
                        varianceratios = 1, conservative = TRUE,detailedoutput = TRUE
)

doe.eval2

#Changing anticoef to achieve conservative power for effect size of 1.5
doe.eval2 <- eval_design(doe2$design,
                         model=~ (x+y+z)^2 + I(x^2),
                         alpha=.2, varianceratios = 1, detailedoutput = TRUE,
                         anticoef = c(.75,.75,.75,0,.75,.75,.75,.75,.75,.75,.75)
)

doe.eval2

**Comment by tylermorganwall** [comment]
Glad you find it useful!

There is a bug here, although it's slightly different than what you're trying to do. For conservative anticipated coefficients (see [Power Analysis Tutorial for Experimental Design Software](http://www.dtic.mil/get-tr-doc/pdf?AD=ADA619843), page 3-21 to 3-27), all of the anticipated coefficients for a factor are set to zero except for the one with the lowest parameter power, with the one exception of there being a tie. When there is a tie, the anticipated coefficients corresponding to the equal parameter powers are given alternating signs with the same magnitude. Thus, your conservative anticipated coefficients should be:
```r
c(0.75, 0.75, 0.75, 0.75, -0.75, 0.75, 0.75, 0.75, -0.75, 0.75, -0.75)
```
rather than:
```r
c(0.75, 0.75, 0.75, 0.75, 0, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75)
```
The bug is cancelling out the sign change, and is fixed in the latest version.

Might I ask, why are you using AlgDesign rather than the built in function gen_design for generating your design? I see you're replicating the candidate set so you can produce a design larger than the size of the unreplicated candidate set--not having to do that is one of the benefits of skpr's gen_design over optFederov.

Here is the equivalent code for generating the design in skpr itself:

```r
cand.list <- expand.grid(x=c(1,2,3), y=c("Yes","No"), z= c("A","B","C"))
doe2 <- gen_design(cand.list, ~(x+y+z)^2 + I(x^2), trials = 30, repeats=1000)
```
or piped:
```r
expand.grid(x=c(1,2,3), y=c("Yes","No"), z= c("A","B","C")) %>%
  gen_design(~(x+y+z)^2 + I(x^2), trials = 30, repeats=1000) %>%
  eval_design(~(x+y+z)^2 + I(x^2), alpha=0.2, effectsize = 1.5, conservative = TRUE)
```
Note that I removed the varianceratios argument to eval_design, as that argument only changes the output when the input is a split-plot design. There is also no need to randomize the order of the candidate set for gen_design, as it internally does that for you.

**Comment by Rookie323** [comment]
I was using AlgDesign since I was familiar and planned to dig into skpr later.  

I apologize I meant factor 'z' is giving me the issue.  Currently I have skpr_0.45.2.zip installed.  Is this the latest version?  I tried install.packages("skpr") again and this was the latest version installed.

I ran your piped code and

**Comment by tylermorganwall** [comment]
The version you get with `install.packages("skpr")` is from the CRAN, which is updated on a much less frequent basis than the package itself. Try installing the package "devtools" and installing the latest version from here:

```r
install.packages("devtools")
devtools::install_github("tylermorganwall/skpr")
```

**Comment by Rookie323** [comment]
I will close this issue.  Thanks for all the help.  Had some issues installing but that was due to my virus scanner and firewall.
