### ISSUE TITLE
G-Optimality not computed when generating G optimal design

### ISSUE THREAD

**Issue by dennisjmoritz** [tylermorganwall/skpr#70]
When generating a g-optimal design using gen_design() no g-efficiency values are generated. Further, I suspect the generated design is not g-optimal. The g efficiency calculations can be forced using the g_efficiency_method option, but the generated design still is g-sub optimal.

Example:

```
# Generating candidate set:
candidateset = expand.grid(X1 = seq(-1,1, length.out = 3),
                           X2 = seq(-1,1, length.out = 3))

# Generating design:
design = gen_design(candidateset = candidateset,
                    model = ~X1 + X2 + X1:X2,
                    trials = 12,
                    optimality = "G")
get_optimality(design)
```

With g_effeciency_method

```
# Generating design:
design = gen_design(candidateset = candidateset,
                    model = ~X1 + X2 + X1:X2,
                    trials = 12,
                    optimality = "G",
                    advancedoption= list(
g_efficiency_method = "random"))
get_optimality(design)
```

**Comment by tylermorganwall** [comment]
Why do you suspect the design generated is not G-optimal?

**Comment by dennisjmoritz** [comment]
When comparing a design generated to be G-optimal to a design which is D-optimal, the design which is D-optimal will have higher G-efficiencies than the design generated to be G-optimal.

**Comment by tylermorganwall** [comment]
Designs generated as G-optimal will now report that value when calling `get_optimality()`.

To your concern about G-optimality, D-optimality and G-optimality are closely linked (designs that are D-optimal will often be G-optimal) but G-optimality is a min-max criteria, which is much more difficult to optimize directly. Since G-efficiency is computed via random sampling of the space and is just an estimate of the true G-efficiency, you may run into occasions where a D-optimal design is very close (or identical) to the G-optimal design, but the G-efficiency estimate is higher. See the advancedoptions documentation on how to control the number of random samples.
